// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://urrripwnsxajbdvkzffb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVycnJpcHduc3hhamJkdmt6ZmZiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2ODE5NTMsImV4cCI6MjA3MDI1Nzk1M30.741M-sWEweaB06wvWemPkqluXKKwHOjVX0-Y8VjfbAI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});